import {
  Activity,
  BadgeCheck,
  Boxes,
  BriefcaseBusiness,
  Building2,
  Calculator,
  ClipboardCheck,
  Compass,
  FileCheck2,
  FileText,
  FileWarning,
  Handshake,
  Landmark,
  LockKeyhole,
  MailWarning,
  Map,
  ReceiptText,
  RefreshCw,
  Rocket,
  Route,
  Search,
  ShieldCheck,
  TrendingUp,
  Users,
  type LucideIcon,
} from "lucide-react";

/** Chave usada em `ServiceCard.icon` nos arquivos de conteúdo → componente Lucide. */
export const serviceIconMap: Record<string, LucideIcon> = {
  activity: Activity,
  badge: BadgeCheck,
  boxes: Boxes,
  briefcase: BriefcaseBusiness,
  building: Building2,
  calculator: Calculator,
  clipboard: ClipboardCheck,
  compass: Compass,
  "file-check": FileCheck2,
  "file-text": FileText,
  "file-warning": FileWarning,
  handshake: Handshake,
  landmark: Landmark,
  lock: LockKeyhole,
  "mail-warning": MailWarning,
  map: Map,
  receipt: ReceiptText,
  refresh: RefreshCw,
  rocket: Rocket,
  route: Route,
  search: Search,
  shield: ShieldCheck,
  trending: TrendingUp,
  users: Users,
};
